[package]
name = "overbrowsered"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"

[target.'cfg(target_os = "linux")'.dependencies]
atspi = "0.30"
freedesktop-desktop-entry = "0.8"
futures-lite = "2"
ksni = { version = "0.3", default-features = false, features = ["async-io"] }
zbus = "5"

[target.'cfg(target_os = "windows")'.dependencies]
winsafe = { version = "0.0.28", features = ["user", "advapi", "shell"] }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_UI_Accessibility",
    "Win32_UI_WindowsAndMessaging",
]
